"use strict";(self.webpackChunkmy_website=self.webpackChunkmy_website||[]).push([[2860],{3905:(e,n,t)=>{t.d(n,{Zo:()=>s,kt:()=>m});var r=t(7294);function o(e,n,t){return n in e?Object.defineProperty(e,n,{value:t,enumerable:!0,configurable:!0,writable:!0}):e[n]=t,e}function i(e,n){var t=Object.keys(e);if(Object.getOwnPropertySymbols){var r=Object.getOwnPropertySymbols(e);n&&(r=r.filter((function(n){return Object.getOwnPropertyDescriptor(e,n).enumerable}))),t.push.apply(t,r)}return t}function a(e){for(var n=1;n<arguments.length;n++){var t=null!=arguments[n]?arguments[n]:{};n%2?i(Object(t),!0).forEach((function(n){o(e,n,t[n])})):Object.getOwnPropertyDescriptors?Object.defineProperties(e,Object.getOwnPropertyDescriptors(t)):i(Object(t)).forEach((function(n){Object.defineProperty(e,n,Object.getOwnPropertyDescriptor(t,n))}))}return e}function l(e,n){if(null==e)return{};var t,r,o=function(e,n){if(null==e)return{};var t,r,o={},i=Object.keys(e);for(r=0;r<i.length;r++)t=i[r],n.indexOf(t)>=0||(o[t]=e[t]);return o}(e,n);if(Object.getOwnPropertySymbols){var i=Object.getOwnPropertySymbols(e);for(r=0;r<i.length;r++)t=i[r],n.indexOf(t)>=0||Object.prototype.propertyIsEnumerable.call(e,t)&&(o[t]=e[t])}return o}var p=r.createContext({}),c=function(e){var n=r.useContext(p),t=n;return e&&(t="function"==typeof e?e(n):a(a({},n),e)),t},s=function(e){var n=c(e.components);return r.createElement(p.Provider,{value:n},e.children)},d="mdxType",h={inlineCode:"code",wrapper:function(e){var n=e.children;return r.createElement(r.Fragment,{},n)}},u=r.forwardRef((function(e,n){var t=e.components,o=e.mdxType,i=e.originalType,p=e.parentName,s=l(e,["components","mdxType","originalType","parentName"]),d=c(t),u=o,m=d["".concat(p,".").concat(u)]||d[u]||h[u]||i;return t?r.createElement(m,a(a({ref:n},s),{},{components:t})):r.createElement(m,a({ref:n},s))}));function m(e,n){var t=arguments,o=n&&n.mdxType;if("string"==typeof e||o){var i=t.length,a=new Array(i);a[0]=u;var l={};for(var p in n)hasOwnProperty.call(n,p)&&(l[p]=n[p]);l.originalType=e,l[d]="string"==typeof e?e:o,a[1]=l;for(var c=2;c<i;c++)a[c]=t[c];return r.createElement.apply(null,a)}return r.createElement.apply(null,t)}u.displayName="MDXCreateElement"},8403:(e,n,t)=>{t.r(n),t.d(n,{assets:()=>p,contentTitle:()=>a,default:()=>h,frontMatter:()=>i,metadata:()=>l,toc:()=>c});var r=t(7462),o=(t(7294),t(3905));const i={sidebar_position:6,id:"error-handling-and-exception-handling",title:"Error Handling and Exception Handling",tags:["Python","Error Handling","Exception Handling"]},a=void 0,l={unversionedId:"tuts/tutorials/programming/python/error-handling-and-exception-handling",id:"tuts/tutorials/programming/python/error-handling-and-exception-handling",title:"Error Handling and Exception Handling",description:"Errors and exceptions are an inevitable part of programming. Python provides a robust error handling mechanism to catch and handle these errors gracefully. In this section, we'll explore how to handle errors and exceptions effectively in Python.",source:"@site/docs/tuts/tutorials/programming/python/6-error-exception-handling.md",sourceDirName:"tuts/tutorials/programming/python",slug:"/tuts/tutorials/programming/python/error-handling-and-exception-handling",permalink:"/main-website/docs/tuts/tutorials/programming/python/error-handling-and-exception-handling",draft:!1,tags:[{label:"Python",permalink:"/main-website/docs/tags/python"},{label:"Error Handling",permalink:"/main-website/docs/tags/error-handling"},{label:"Exception Handling",permalink:"/main-website/docs/tags/exception-handling"}],version:"current",sidebarPosition:6,frontMatter:{sidebar_position:6,id:"error-handling-and-exception-handling",title:"Error Handling and Exception Handling",tags:["Python","Error Handling","Exception Handling"]},sidebar:"tutorialSidebar",previous:{title:"Modules and Packages",permalink:"/main-website/docs/tuts/tutorials/programming/python/modules-and-packages."},next:{title:"Working with External Libraries and APIs",permalink:"/main-website/docs/tuts/tutorials/programming/python/working-with-external-libraries-and-apis"}},p={},c=[{value:"The try-except Block",id:"the-try-except-block",level:3},{value:"Handling Specific Exceptions",id:"handling-specific-exceptions",level:3},{value:"The else Block",id:"the-else-block",level:3},{value:"The finally Block",id:"the-finally-block",level:3},{value:"Raising Exceptions",id:"raising-exceptions",level:3},{value:"Github Repo",id:"github-repo",level:3}],s={toc:c},d="wrapper";function h(e){let{components:n,...t}=e;return(0,o.kt)(d,(0,r.Z)({},s,t,{components:n,mdxType:"MDXLayout"}),(0,o.kt)("p",null,"Errors and exceptions are an inevitable part of programming. Python provides a robust error handling mechanism to catch and handle these errors gracefully. In this section, we'll explore how to handle errors and exceptions effectively in Python."),(0,o.kt)("h3",{id:"the-try-except-block"},"The try-except Block"),(0,o.kt)("p",null,"The ",(0,o.kt)("inlineCode",{parentName:"p"},"try-except")," block is used to handle exceptions in Python. The code inside the ",(0,o.kt)("inlineCode",{parentName:"p"},"try")," block is executed, and if an exception occurs, it is caught and handled in the ",(0,o.kt)("inlineCode",{parentName:"p"},"except")," block. Here's a basic example:"),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-python"},'try:\n    # Code that may raise an exception\n    result = 10 / 0\nexcept:\n    # Code to handle the exception\n    print("An error occurred!")\n')),(0,o.kt)("p",null,"In the above code, we attempt to divide 10 by 0, which raises a ",(0,o.kt)("inlineCode",{parentName:"p"},"ZeroDivisionError"),". The ",(0,o.kt)("inlineCode",{parentName:"p"},"except")," block catches this exception and executes the code inside it, printing the error message."),(0,o.kt)("h3",{id:"handling-specific-exceptions"},"Handling Specific Exceptions"),(0,o.kt)("p",null,"You can handle specific exceptions by specifying the type of exception after the ",(0,o.kt)("inlineCode",{parentName:"p"},"except")," keyword. This allows you to provide different handling logic for different types of exceptions. Here's an example:"),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-python"},'try:\n    # Code that may raise an exception\n    result = 10 / 0\nexcept ZeroDivisionError:\n    # Code to handle the ZeroDivisionError\n    print("Cannot divide by zero!")\nexcept ValueError:\n    # Code to handle the ValueError\n    print("Invalid value!")\n')),(0,o.kt)("p",null,"In the above code, we have separate ",(0,o.kt)("inlineCode",{parentName:"p"},"except")," blocks for ",(0,o.kt)("inlineCode",{parentName:"p"},"ZeroDivisionError")," and ",(0,o.kt)("inlineCode",{parentName:"p"},"ValueError"),". Depending on the type of exception that occurs, the corresponding block will be executed."),(0,o.kt)("h3",{id:"the-else-block"},"The else Block"),(0,o.kt)("p",null,"You can also include an ",(0,o.kt)("inlineCode",{parentName:"p"},"else")," block after the ",(0,o.kt)("inlineCode",{parentName:"p"},"except")," block to specify code that should be executed when no exceptions occur. This block is optional. Here's an example:"),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-python"},'try:\n    # Code that may raise an exception\n    result = 10 / 2\nexcept ZeroDivisionError:\n    # Code to handle the ZeroDivisionError\n    print("Cannot divide by zero!")\nelse:\n    # Code to execute if no exceptions occur\n    print("Result:", result)\n')),(0,o.kt)("p",null,"In the above code, the ",(0,o.kt)("inlineCode",{parentName:"p"},"else")," block will be executed if no exception occurs. In this case, it prints the result of the division."),(0,o.kt)("h3",{id:"the-finally-block"},"The finally Block"),(0,o.kt)("p",null,"The ",(0,o.kt)("inlineCode",{parentName:"p"},"finally")," block is used to specify code that should be executed regardless of whether an exception occurred or not. This block is optional but is commonly used for cleanup operations. Here's an example:"),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-python"},'try:\n    # Code that may raise an exception\n    result = 10 / 2\nexcept ZeroDivisionError:\n    # Code to handle the ZeroDivisionError\n    print("Cannot divide by zero!")\nfinally:\n    # Code to execute regardless of exceptions\n    print("End of operation")\n')),(0,o.kt)("p",null,"In the above code, the ",(0,o.kt)("inlineCode",{parentName:"p"},"finally"),' block will always be executed, whether an exception occurred or not. It prints "End of operation" to indicate the end of the try-except block.'),(0,o.kt)("h3",{id:"raising-exceptions"},"Raising Exceptions"),(0,o.kt)("p",null,"You can also manually raise exceptions using the ",(0,o.kt)("inlineCode",{parentName:"p"},"raise")," statement. This allows you to create custom exceptions or raise built-in exceptions based on certain conditions. Here's an example:"),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-python"},'try:\n    age = int(input("Enter your age: "))\n    if age < 0:\n        raise ValueError("Age cannot be negative!")\nexcept ValueError as e:\n    print(str(e))\nelse:\n    print(f"Entered age {age}")\n')),(0,o.kt)("p",null,"In the above code, we ask the user to enter their age. If the entered age is negative, we raise a ",(0,o.kt)("inlineCode",{parentName:"p"},"ValueError")," with a custom error message."),(0,o.kt)("h3",{id:""}),(0,o.kt)("p",null," Summary"),(0,o.kt)("p",null,"In this section, we explored error handling and exception handling in Python. We learned how to use the ",(0,o.kt)("inlineCode",{parentName:"p"},"try-except")," block to catch and handle exceptions, handle specific exceptions, include the ",(0,o.kt)("inlineCode",{parentName:"p"},"else")," and ",(0,o.kt)("inlineCode",{parentName:"p"},"finally")," blocks, and raise exceptions. Proper error handling ensures that your code can gracefully handle unexpected situations and provides a better user experience."),(0,o.kt)("h3",{id:"github-repo"},"Github Repo"),(0,o.kt)("admonition",{type:"info"},(0,o.kt)("p",{parentName:"admonition"},"  You can refer to and clone the code samples for this tutorial from the ",(0,o.kt)("a",{parentName:"p",href:"https://github.com/certifysphere/python-code-samples"},"GitHub repository"),"."),(0,o.kt)("p",{parentName:"admonition"},"  To clone the repository, you can use the following command:"),(0,o.kt)("pre",{parentName:"admonition"},(0,o.kt)("code",{parentName:"pre",className:"language-bash"},"git clone https://github.com/certifysphere/python-code-samples.git\n")),(0,o.kt)("p",{parentName:"admonition"},"  You can then navigate to the ",(0,o.kt)("inlineCode",{parentName:"p"},"/src")," directory to access all the code samples given in this tutorial. ")))}h.isMDXComponent=!0}}]);